### ISSUE TITLE
Erkennung von Downtimes

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/webapp#10]
Können wir eine Erkennung von Downtimes einbauen?

Momentan ist anscheinend das Backend down. Weder Anmelden noch Scans sind möglich.

Wenn wir das vorab durch einen "Ping-Test" prüfen könnten, könnten webapp und freeapp entsprechende Informationen anzeigen.

**Comment by Lednerb** [comment]
Haben wir auf dem Schirm, jedoch an anderer Stelle angesiedelt als bei der webapp.
