### ISSUE TITLE
Domain bestätigen - Domain anzeigen

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/webapp#14]
Auf der "Domain bestätigen" Seite sollte die Domain, um die es geht, angezeigt werden, nicht zuletzt deswegen, weil SIWECOS durchaus die Domain ändern kann:

- Protokoll geändert
- www hinzugefügt
- Pfad abgeschnitten

**Comment by SniperSister** [comment]
Konkrete Idee wo wir das unterbringen? Screenshot mit Pfeil oder so :)

**Comment by Skeeve** [comment]
So vielleicht?

![image](https://user-images.githubusercontent.com/725404/49069155-d9b60b00-f228-11e8-8c49-cd2cf9054650.png)

Allerdings bin ich nicht der Design- und Usability-Experte…

**Comment by Lednerb** [comment]
### Update `v2`

Es ist ausreichend, die Domain anzuzeigen:

1. Es kann ausschließlich ein Hostname (Domain) registriert werden, ohne Protokoll oder Pfadangaben
2. Bei der Verifizierung wird zunächst das `http://` Protokoll getestet und einer Weiterleitung zu `https://` gefolgt
3. Es wird kein `www.` mehr angehängt oder abgeschnitten

Kann eine Domain nicht verifiziert werden, weil bspw. die `www.`-Subdomain nicht erreichbar ist, so wird eine entsprechende Fehlermeldung ausgegeben.

-----------------------------------------------
@Skeeve bitte schließen, falls sich das Issue damit erledigt hat.
