### ISSUE TITLE
Sprachauswahl speichern und anzeigen

### ISSUE THREAD

**Issue by Lednerb** [SIWECOS/webapp#15]
Siehe https://github.com/SIWECOS/siwecos-business-layer/pull/87

Es soll dem Nutzer die Option gegeben werden, seine bevorzugte Sprache einstellen zu können.

Das Feld `preferred_language` kann auch beim Registrieren des Nutzers gesendet werden, bspw. direkt über die bestehende Sprachauswahl beim Registrierungsvorgang.

Erlaubt sind für `preferred_language`  die Strings `de` und `en`.

Wird keine `preferred_language` gesendet, so ist der Standard `de`.

**Comment by Lednerb** [comment]
Nach merging von #16 folgendes:
Ich versuche auf der Englischen Einstellung meine Daten zu aktualisieren, doch es wird jeweils nur `"preferred_language": "de"` geschickt.

**Comment by SniperSister** [comment]
![voila_capture 2018-12-12_07-45-41_am](https://user-images.githubusercontent.com/498096/49851671-20d3fc80-fde2-11e8-8067-3740badd7c97.png)

Kann ich nicht reproduzieren, wird bei mir in der Staging korrekt gesetzt?

**Comment by Lednerb** [comment]
Bei meinem Test hatte ich mich nicht registriert, sondern die Account-Daten aktualisiert (Adresse etc.).
Da wurde dann die neue Sprache (`en`) nicht mit geschickt.

**Comment by Skeeve** [comment]
Wie schaut's hier aus?

**Comment by SniperSister** [comment]
ist in der neuen version gefixt
