### ISSUE TITLE
Flackern / Menü reagiert erst nach 2. Klick

### ISSUE THREAD

**Issue by Lednerb** [SIWECOS/webapp#17]
Beim Klick auf "My Account", wenn die Sprache gewechselt wird, wird die entsprechende Seite erst nach einem 2. Klick angezeigt. Außerdem *flackert* die Seite etwas.

![bug-my-account](https://user-images.githubusercontent.com/2056876/49957357-d351af80-ff07-11e8-98e5-334e096fe039.gif)

**Comment by SniperSister** [comment]
In der Staging gefixt, bitte checken

**Comment by Lednerb** [comment]
Fixed.
