### ISSUE TITLE
Aktivierungsmail erneut verschicken

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/webapp#18]
Wir haben den Fall, daß ein Kunde die Aktivierungsmail nicht erhalten hat. Fehlkonfiguration auf seiner Seite.

Wenn man versucht sich anzumelden, wird man aufgefordert, zuerst den Account zu aktivieren. Hier wäre es gut, einen Link zu haben, der die Aktivierungsmail erneut verschickt. 

Zugehöriges Ticket https://github.com/SIWECOS/siwecos-business-layer/issues/94

**Comment by Lednerb** [comment]
Kann implementier werden, siehe: https://github.com/SIWECOS/siwecos-business-layer/issues/94#issuecomment-467372582

**Comment by Lednerb** [comment]
Kann implementiert werden, siehe [BLA DOKU](https://siwecos.github.io/siwecos-business-layer/#resend-activation-mail)

**Comment by SniperSister** [comment]
Kann in #29

**Comment by SniperSister** [comment]
Link ist drin
