### ISSUE TITLE
Style-Bug "Mehr Informationen"

### ISSUE THREAD

**Issue by Lednerb** [SIWECOS/webapp#20]
Beim Klick auf "Mehr Informationen" für einen Test eines Scanners bleibt dieses im dunklen Rot. Der Text ist nicht lesbar bei `focus` oder `hover` state.

Vielleicht die Schrift auf Weiß anpassen etc.

![Bildschirmfoto vom 2019-03-28 11-51-51](https://user-images.githubusercontent.com/2056876/55152318-6a0d4980-5150-11e9-9ea5-91edbc980a78.png)

Getestet im aktuellen Chromium und Firefox.

**Comment by SniperSister** [comment]
Fixed
