### ISSUE TITLE
Toggle Mehr Informationen / Weniger Informationen

### ISSUE THREAD

**Issue by Lednerb** [SIWECOS/webapp#21]
Nach einem klick auf "Mehr Informationen" kann man die eingeblendete auch wieder ausblenden.

Dies geschieht über einen weiteren Klick auf "Mehr Informationen".
Da sowieso getoggled wird, wäre es schön, wenn der String "Mehr Informationen" dann nach Aktivierung auf "Weniger Informationen" ebenfalls gewechselt wird.

![Bildschirmfoto vom 2019-03-29 19-37-28](https://user-images.githubusercontent.com/2056876/55255276-84334e80-525a-11e9-82ce-b695a08a3795.png)

**Comment by SniperSister** [comment]
Fixed, bitte testen

**Comment by Lednerb** [comment]
Funktioniert einwandfrei :+1: 

Bitte auch in freescan app übernehmen, dann Issue schließen.

**Comment by SniperSister** [comment]
Erledigt
