### ISSUE TITLE
Proposal: Webapp-Designüberarbeitung

### ISSUE THREAD

**Issue by svom** [SIWECOS/webapp#22]
Hallo zusammen,

Gerne würde ich einen Vorschlag zur Überarbeitung des UIs der Webapp einreichen.

Diese macht es einfacher eine Vielzahl von Seiten inkl. der entsprechenden detaillierten Scan-Ergebnisse zu überprüfen.

Zum einen wurden hierzu die Abstände und Schriftgrößen angepasst, um die visuelle Hierarchie im Vergleich zum aktuellen Stand zu verstärken. Dadurch werden Inhalte besser strukturiert und entsprechend auch einfacher zu erfassen.

Zudem wurden sekundäre Aktionen (bspw. das entfernen einer Domain) weniger prominent gestaltet. Der Fokus liegt so auf den Testergebnissen. 

Erfolgreich absolvierte Tests werden in diesem Kontext auch erst auf Wunsch des Nutzers dargestellt. Dadurch werden etwaige Handlungsempfehlungen zur Absicherung der Seite in den Fokus gerückt.

Das neue Design beachtet zudem die detailierte Auflistung von URLs für den Fall das eine komplette Seite gecrawlt wird.

Link zum Prototypen: 
https://sketch.cloud/s/RdROl/paekveR/play

Einzelansichten als PNG:
![Detail 2nd Level](https://user-images.githubusercontent.com/14434412/55413908-83583080-556a-11e9-9fc5-cf527a71038b.png)
![Detail](https://user-images.githubusercontent.com/14434412/55413910-83583080-556a-11e9-94ac-240e96dbd6a3.png)
![Overview](https://user-images.githubusercontent.com/14434412/55413912-83f0c700-556a-11e9-881b-d2e1e5646433.png)

Liebe Grüße
Lukas Jardin

**Comment by PetraStruck** [comment]
Sieht für mich sehr stimmig und übersichtlich aus.

**Comment by Skeeve** [comment]
Wenn die Gauges Links zu den Einzelergebnissen sind, damit man direkt dahin "hüpfen" kann, gefällt's mir. Schön wäre dann bei den Einzelergbnissen Ein Link zum "Zurückhüpfen".

Wie seiht die Übersicht bei 5 Scannern aus? Bei 7 oder bei einer größeren Primzahl? ;)

**Comment by Lednerb** [comment]
Sehr cool und eine __deutliche__ Verbesserung zum aktuellen Stand.

Ich nehme an, dass wir dann auch direkt die Scores per CSS gestalten können und nicht extra ein berechnetes SVG mitliefern müssen?

Bei der Übersicht würde ich jedoch einzeln die *Domain* und nicht die URL anzeigen, (`sehr-langer-domain-name.de`), da wir darunter aufgeschlüsselt ja mehrere URLs haben können, sobald der Crawler eingesetzt wird.

Die Scanner-Übersicht kann dann sehr gerne auch leicht animiert sein, bspw. beim Hover etwas größer werden, bei Click direkt zum Scanner-Report gescrollt werden.

**Comment by SniperSister** [comment]
> Ich nehme an, dass wir dann auch direkt die Scores per CSS gestalten können und nicht extra ein berechnetes SVG mitliefern müssen?

Das ist auch aktuell nicht notwendig, das SVG baue ich mir Client-Side

**Comment by svom** [comment]
> Wie sieht die Übersicht bei 5 Scannern aus? Bei 7 oder bei einer größeren Primzahl? ;)

Bei fünf Scannern würde ich eine Kombination aus 3- und 2-spaltiger Darstellung wählen, wobei die Reihe mit weniger Spalten zentriert wird. Genau so verhält es sich bei 7 oder anderen größeren Primzahlen.

**Comment by Skeeve** [comment]
Sorry, @svom… Die Frage ging eher in die Richtung: "Passiert das automagisch? Oder muß dann eingegriffen werden ums Layout anzupassen?"

Ich fände eine vorbereitete "Magie" (minimal für 1-20 Scanner) nicht schlecht.

Das wäre eine Erleichterung, weil es dann eine Baustelle weniger zum Ändern gäbe, wenn Scanner hinzukommen oder wegfallen.

**Comment by svom** [comment]
@Skeeve Achso, dann vergiss was ich gesagt habe! :)

**Comment by Skeeve** [comment]
Ich denke, die einfachste Magie könnte sein: Immer 4er-Reihen und alle zentriert.

```
4er-Rest 0 | 4er-Rest 1 | 4er-Rest 2 | 4er-Rest 3 |
  O O O O  |   O O O O  |   O O O O  |   O O O O  |
  O O O O  |      O     |     O O    |    O O O   |

```

**Comment by ic0ns** [comment]
Hey, erstmal gut Arbeit. Sieht cool aus. Frage: Können wir diesen String "Überprüfung auf..." loswerden/austauschen. Statt "Überprüfung auf CSP" - "Probleme in der CSP" oder halt - "Keine Probleme in der CSP" o.Ä. Aktuell ist das nur eine nichts sagende Überschrift.

**Comment by Skeeve** [comment]
Hi Robert!

Die möchtest Du ja schon lange loswerden. Ich habe auch schon mit @Lednerb darüber am Dienstag gesprochen.

Die Überschrift mag Dir nutzlos erscheinen, weil die wirklich wichtige Information ja erst darunter liegt. Von daher erscheint sie absolut redundant.

Allerdings hat sie einen großen Vorteil für unser Zielpublikum, KMUs. Warum? Nun: Wir gehen davon aus, dass viele dieser Unternehmen Fachleute beauftragen werden, um ihre Weseite sicher zu gestalten, nachdem sie bei uns auf ein Problem aufmerksam wurden.

Wenn dieser Fachmann dann dran war, sind die Vorher- und Nachher-Reports aber nicht mehr einfach vergleichbar.

Im Moment heißt es "Überprüfung der Verschlüsselungsstärke des Zertifikats". Später sind es unterschiedliche Texte, je nach Ausgang des Tests. Das macht es gegebenenfalls schwieriger, die veränderten Ergebnisse einander zuzuordnen.

**Comment by PetraStruck** [comment]
https://projekte.djumla.de/siwecos/dummy-preview# - Gefällt mir, ist übersichtlich und gut unterteilt. Ich würde die Scoregrafik pro gescannter Website noch hinzufügen. Oder erscheint die anstelle der 23? Ich meine ungefähr so:

![score3](https://user-images.githubusercontent.com/47851250/57369563-29acdc80-718e-11e9-8824-7cf155cb1305.png)
