### ISSUE TITLE
Login notwendig, dennoch logged-in Menü

### ISSUE THREAD

**Issue by Lednerb** [SIWECOS/webapp#24]
Beim Neuladen der Seite ergibt sich folgendes Bild:

![Bildschirmfoto von 2019-08-12 12-43-08](https://user-images.githubusercontent.com/2056876/62862023-752ed380-bd05-11e9-9e98-d13bd9852cdc.png)

Der Nutzer sieht u.a. einen "Abmelden"-Link in der Navigationsleiste, muss sich aber dennoch anmelden, um auf seinen Account zuzugreifen.

**Comment by SniperSister** [comment]
Ist für mich nicht reproduzierbar

**Comment by Lednerb** [comment]
Gerade erneut getestet: Fehler tritt lediglich in `staging` auf

**Comment by SniperSister** [comment]
Das Access Token liegt im localstorage und der greift für staging und live, daher wird mit dem live-token ein login im staging probiert, was dann erwartungsgemäß fehlschlägt.
