### ISSUE TITLE
Anzeige Datum nicht korrekt

### ISSUE THREAD

**Issue by Lednerb** [SIWECOS/webapp#25]
Das Datum wird unterhalb der Scans nicht korrekt formatiert ausgegeben.

Zeit müsste in diesem Beispiel bei 18:27 sein.

Ebenso in der webapp-freescan

![Bildschirmfoto von 2019-08-22 18-37-35](https://user-images.githubusercontent.com/2056876/63533067-594cde00-c50c-11e9-9caf-b41d76cc2e61.png)

**Comment by SniperSister** [comment]
Das Datumsformat aus der API ist in der Staging anders als in der Live, Anpassung an der Webapp wird gerdae deployed

**Comment by Lednerb** [comment]
Passt jetzt für die einzelnen Scanner, jedoch wird das "Haupt-Scan-Datum" falsch angezeigt:

![Bildschirmfoto von 2019-08-23 11-36-36](https://user-images.githubusercontent.com/2056876/63583005-6e704e00-c59a-11e9-91e2-1541ae215dae.png)

Direkt unter den Buttons sollte 11:33 stehen.

**Comment by SniperSister** [comment]
> Passt jetzt für die einzelnen Scanner, jedoch wird das "Haupt-Scan-Datum" falsch angezeigt:

Das Datumsformat ist dort noch ein anderes, damit kann die JS lib  nicht umgehen:

![Voila_Capture 2019-09-04_03-42-49_PM](https://user-images.githubusercontent.com/498096/64260169-af694a80-cf2a-11e9-8beb-d099956e4f03.png)

**Comment by Lednerb** [comment]
In `staging` jetzt angepasst.

Es wird jetzt überall unter der `v1` route das obere Datumsformat genutzt.

Momentan haben wir daher -2h.

**Comment by SniperSister** [comment]
fixed

**Comment by Lednerb** [comment]
![Bildschirmfoto von 2019-09-04 17-10-22](https://user-images.githubusercontent.com/2056876/64267579-ef362f00-cf36-11e9-9212-74f6bf1ac110.png)


Freescan ist 2 Stunden in der Zukunft

**Comment by SniperSister** [comment]
Live oder Staging?

**Comment by Lednerb** [comment]
Live, staging funktioniert.

**Comment by SniperSister** [comment]
Der Freescan returned bei den einzelscannern noch nicht das korrekte datumsformat

**Comment by Lednerb** [comment]
Erledigt
