### ISSUE TITLE
PDF-Integration: Route anpassen

### ISSUE THREAD

**Issue by Lednerb** [SIWECOS/webapp#26]
Für Version 2 der Webapp müsste noch die Route zum Download des PDF Reports angepasst werden.

Weitere Informationen:

https://siwecos.github.io/siwecos-business-layer/#retrieving-the-scan-report-as-pdf

**Comment by SniperSister** [comment]
Der Aufruf ist für die Webapp problematisch. Der PDF-Button soll ein neues Browser-Fenster öffnen, somit läuft das außerhalb der Webapp als nativer browser aufruf - dort kann ich wiederrum keine eigenen header mitübergeben, weshalb das SIWECOS-Token nicht mit übergeben werden kann.

Lösungsidee? Token auch via GET übergebbar machen?

**Comment by Lednerb** [comment]
Was spricht gegen ein Ajax Post Request?

Starten eines neuen Scans wird ja ebenso realisiert?

Vorteil: Der Nutzer hat im Anschluss keinen offenen Tab mit der api-url

**Comment by SniperSister** [comment]
Na, der Nutzer soll sich das PDF ja anschauen / runterladen können, wie soll das über einen AJAX Post gehen?

**Comment by Lednerb** [comment]
Ähm... ja klar. Gut ich passe das so an, dass du das Token via GET Parameter senden kannst.

**Comment by Lednerb** [comment]
Done via https://github.com/SIWECOS/siwecos-business-layer/commit/0b72ba75c6fadb271840278254960df8e9eb1c05

Dokumentation ist dementsprechend angepasst.

**Comment by SniperSister** [comment]
Thx, deploy läuft

**Comment by Lednerb** [comment]
Funktioniert. Sehr gut.
