### ISSUE TITLE
Refactoring SIWECOS frontend

### ISSUE THREAD

**Issue by sven-ahrens** [SIWECOS/webapp#29]
* [x] Implement the new version of the SIWECOS API
* [x] Wrapping basic HTML structure around .vue components
* Affected views:
* * [x] Login
* * [x] Forgot Password
* * [x] Reset Password
* * [x] Reset Activation
* * [x] Account
* * [x] Account Delete
* * [x] Logout
* * [x] Registration
* * [x] Domain Add
* * [x] Domain Verify
* * [x] Domain List
* [x] Multi language support
* [x] Implement the Vue.js routing system and take over the old route names
* [x] Implement css class: ``button--link``
* [x] PDF Report Link

**Comment by SniperSister** [comment]
@Lednerb mach dafür bitte einzelne Tickets, dann können wir den Status leichter tracken

**Comment by SniperSister** [comment]
Basisimplementierung ist Feature Complete, Rest in den einzelnen Tickets – mache hier zu und Licht aus :)
