### ISSUE TITLE
Mailadresse ändern - Verbesserungsvorschläge

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/webapp#33]
Wenn man seine Mailadresse auf eine vergebene Adresse ändern möchte erscheint nur die Universalfehlermeldung, dass nicht gespeichert werden konnte. BLA liefert hier einen 422 mit `{"email":["validation.unique"]}`. Man könnte also eine hilfreichere Meldung anzeigen.

Wenn das Ändern erfolgreich war, sollte ein Hinweis kommen, dass die Adresse erst nach Aktivierung gültig ist und bis dahin noch die alte gilt.

**Comment by SniperSister** [comment]
Kann in #29

**Comment by Skeeve** [comment]
Wie schaut's damit aus?

**Comment by SniperSister** [comment]
Durch validierungsnachicht abgefangen
