### ISSUE TITLE
Jumps im Sicherheitsbericht

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/webapp#37]
Schön wäre es, man könnte von den Gauges (Tachos?) oben in den Details (Also der Scan Übersicht) des Sicherheitsberichts zu den Ergebnissen unten springen. Wenn ich also sehe, dass ein Scanner rot ist, kann ich so leicht unten seine Einzelergebnisse finden.

Vielleicht dann auch noch gleich einen "Zurück zur Übersicht" Link bei den Scannerergebnissen, der mich zurück zu den Gauges führts.

**Comment by SniperSister** [comment]
fixed via #50, deploy läuft
