### ISSUE TITLE
Zentrierter Scanner Test?

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/webapp#38]
![image](https://user-images.githubusercontent.com/725404/65503868-1e9ce380-dec6-11e9-8069-400231b115d1.png)

Zweizeilige Scanner Test Überschriften scheinen zentriert zu werden.

Wollen wir das wirklich?

**Comment by SniperSister** [comment]
Deploy läuft, bitte in 5min checken.

Side note: warum wird HPKP überhaupt angezeigt?

**Comment by Lednerb** [comment]
HPKP hat als `scanType` eig. `hidden`. Wird dann wahrscheinlich noch nicht berücksichtigt?

**Comment by SniperSister** [comment]
Fixed
