### ISSUE TITLE
Box hevorheben?

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/webapp#39]
Die Boxen im Webinterface rechts (Kontobox etc.) werden bei mouseover hervorgehoben (Schatten)

![image](https://user-images.githubusercontent.com/725404/65504038-7e938a00-dec6-11e9-823f-5355e7646c76.png)

Sollten wir das aus Konsistenzgründen auch in der Domainübersicht machen?

**Comment by SniperSister** [comment]
Done: https://github.com/SIWECOS/siwecos-website/commit/f95c9f6315f9340a1041c15360cd56950c80bf7d
