### ISSUE TITLE
Domain verifizieren anstatt Scan starten Button

### ISSUE THREAD

**Issue by Lednerb** [SIWECOS/webapp#41]
Obwohl die Domain verifiziert wurde, wird anstatt des `Scan starten` Buttons noch der Domain-Verifizierungs-Schritt angezeigt.

![Bildschirmfoto von 2019-09-24 12-09-23](https://user-images.githubusercontent.com/2056876/65509569-0c757200-ded3-11e9-92e3-303e221ad7a8.png)

**Comment by SniperSister** [comment]
Indirekt durch #45 gefixt
