### ISSUE TITLE
Hostname anstelle von URL für Domain hinzufügen

### ISSUE THREAD

**Issue by Lednerb** [SIWECOS/webapp#42]
Beim Hinzufügen einer neuen Domain muss bislang weiterhin eine URL eingegeben werden.

Es wäre schöner, hier direkt den Hostname eintragen zu können.

![Bildschirmfoto von 2019-09-24 12-06-18](https://user-images.githubusercontent.com/2056876/65509448-d0421180-ded2-11e9-92ae-1cf79e524a8a.png)

**Comment by SniperSister** [comment]
Fixed
