### ISSUE TITLE
[staging] Domainverifizierung funktioniert nicht richtig.

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/webapp#49]
1. Domain eingetragen
2. meta token auf der Webseite hinterlegt
3. "Bestätigen" geklickt -> Keine Reaktion
4. "Bestätigen" geklickt -> Die Domain ist bereits registriert
5. Zurück zur Domainübersicht -> Domain erscheint "unbestätigt"
6. In der DB ist sie bestätigt.
7. Abmelden
8. Anmelden
9. Domain wird als bestätigt angezeigt

**Comment by Lednerb** [comment]
Aktuell folgendes Problem:

1. Domain hinzufügen
2. Token auf Seite hinterlegen
3. Klick auf Verifizieren

Die Domain wird erfolgreich verifiziert, allerdings erfolgt keine Weiterleitung zur Domainübersicht.

**Comment by SniperSister** [comment]
Fixed
