### ISSUE TITLE
Neuen Scan starten - Button bleibt aktiv

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/webapp#5]
Wenn ich einen neuen Scan starte, bleibt der Button aktiv. Er sollte ausgegraut disabled sein, solange der Scan läuft (Siehe "alte" webapp)

**Comment by SniperSister** [comment]
Ist kein Problem der Webapp sondern der Website, dort fehlten schlicht die disabled-Styles um das korrekt gesetzt Attribut auch grafisch sichtbar zu machen. Bitte in der Staging prüfen.

**Comment by SniperSister** [comment]
Bitte erst closen wenn es auch final gelöst ist. Habe die Farbe nochmal angepast, nach deploy bitte prüfen

**Comment by Skeeve** [comment]
![image](https://user-images.githubusercontent.com/725404/46537098-bd44c480-c8b0-11e8-9997-778b80e79265.png)
Mir fällt's schwer, die Schrift zu lesen.

Es funktioniert nicht, weil Du !important verwendest

![image](https://user-images.githubusercontent.com/725404/46537248-13196c80-c8b1-11e8-9b9d-d0917822a249.png)

**Comment by SniperSister** [comment]
Fixed
