### ISSUE TITLE
Nutzer Registrierung - Bestätigung verbessern

### ISSUE THREAD

**Issue by Lednerb** [SIWECOS/webapp#53]
Nach der Registrierung wird folgendes angezeigt:

![Bildschirmfoto von 2019-10-15 11-03-28](https://user-images.githubusercontent.com/2056876/66817204-a3b27000-ef3b-11e9-890c-d4891f9c4acf.png)

Eventuell kann man den Button nach erfolgter Registrierung ausblenden und / oder weitere Instruktionen dem Nutzer anzeigen, wie bspw.: E-Mail Checken und anschließend einloggen.

**Comment by SniperSister** [comment]
Geht es um die Bestansdapp? Oder die neue?

**Comment by Lednerb** [comment]
Beide (wobei es ausreichend ist, dies in der neuen Variante zu berücksichtigen.)

Screenshot und Test kommen aus der aktuellen `staging` Version.

**Comment by sven-ahrens** [comment]
> Eventuell kann man den Button nach erfolgter Registrierung ausblenden

Finde ich eher unüblich im Web, dass nach der Registrierung einfach nur der Button ausgeblendet wird.

> und / oder weitere Instruktionen dem Nutzer anzeigen, wie bspw.: E-Mail Checken und anschließend einloggen.

Ich weiß nicht, wie die Zielgruppe von SIWECOS aussieht, aber ich gehe mal davon aus, dass die meisten schon mal eine Registrierung abgeschlossen haben und wissen, wie das geht.

Ich würde stattdessen vorschlagen, dem Benutzer eine Erfolgsnachricht oder eben eine Fehlermeldung zurückzugeben (vielleicht über einen Popup?) und daraufhin eine Weiterleitung auf die Login-Seite zu veranlassen.

**Comment by Lednerb** [comment]
@sven-ahrens 

Ursprüngliche Zielgruppe sind Nicht-Techniker in KMUs.

Mit deinem Vorschlag gehe ich mit.

**Comment by sven-ahrens** [comment]
Supi. Merke ich mir dann vor!

**Comment by SniperSister** [comment]
Mit #55 erledigt
