### ISSUE TITLE
Textausgabe besser formatieren

### ISSUE THREAD

**Issue by Lednerb** [SIWECOS/webapp#54]
Wenn der Übersetzungstext zu lange wird, bricht der Text mit zu wenig Abstand um.

Außerdem gibt es einen unschönen Umbruch bei `Mehr Informationen`

![Bildschirmfoto von 2019-10-16 20-19-34](https://user-images.githubusercontent.com/2056876/66947010-668cd180-f052-11e9-9634-040e24ea3004.png)

**Comment by SniperSister** [comment]
Fixed
