### ISSUE TITLE
[staging] Registrierung weist nicht auf Aktivierungsmail hin

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/webapp#56]
Beim Registrieren wird nur ein Dialog angezeigt, der nicht auf die Aktivierungsmail hinweist.

<img width="253" alt="image" src="https://user-images.githubusercontent.com/725404/67186372-42c9e280-f3e8-11e9-8e45-86cb1400d50a.png">

**Comment by Skeeve** [comment]
Ich nehme einfach mal den Text aus Prod:

> Vielen Dank für Ihre Anmeldung bei SIWECOS! Bitte aktivieren Sie nun Ihr Konto, indem Sie den Bestätigungslink aufrufen, den wir Ihnen per E-Mail zugesendet haben.

**Comment by SniperSister** [comment]
Fixed
