### ISSUE TITLE
[staging] Wollen Sie DIESE Domain wirklich löschen?

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/webapp#58]
Vorschlag: Statt "diese" den Domainnamen anzeigen.

Also statt

![image](https://user-images.githubusercontent.com/725404/67266693-175efa80-f4b1-11e9-9368-52090e05854d.png)

![image](https://user-images.githubusercontent.com/725404/67266828-6573fe00-f4b1-11e9-91d4-b5e284f0738b.png)

**Comment by sven-ahrens** [comment]
Würde es persönlich dann eher in: "Möchten Sie die Domain: "siwecos.de" wirklich löschen?

Nochmal zu wiederholen, dass es seine Domain ist... weiß nicht. Ist ja irgendwie klar, wenn er bei SIWECOS eingeloggt ist, dass dort seine Domains angezeigt werden

**Comment by Skeeve** [comment]
Mach wie Du meinst. Mir ist nur wichtig, dass der Kunde sieht, welche Domain er da löschen wird.

**Comment by sven-ahrens** [comment]
Ok!

**Comment by SniperSister** [comment]
Fixed
