### ISSUE TITLE
Integration der v3-ScanReports

### ISSUE THREAD

**Issue by Lednerb** [SIWECOS/webapp#59]
Zum Abschluss von https://github.com/SIWECOS/siwecos-business-layer/issues/133 müssen noch die zwei neuen BLAv3 Endpunkte an die Webapp angeschlossen sowie das Design entsprechend angepasst werden.

Die Dokumentation zu den beiden Endpoints befindet sich hier:

1. [SiwecosScanReport](https://siwecos.github.io/siwecos-business-layer/#retrieving-the-full-scan-report)
2. [SiwecosScanReport als PDF](https://siwecos.github.io/siwecos-business-layer/#retrieving-the-full-scan-report-as-pdf)

Für die Scanner-Score-Übersicht befindet sich die berechnete Kalkulation zur Verwendung ebenfalls in der Ausgabe.

Die `reports` haben jeweils als key die entsprechende URL oder MailDomain, welche gescannt wurde.

Dadurch lässt sich bspw. leicht ein Accordion-Menü generieren, bei welchem man je eine Zeile mit der URL / MailDomain und dem jeweiligen Score anzeigen kann, welche per Klick ausklappt und den gesamten Report wie in v2 anzeigt.

**Comment by SniperSister** [comment]
Das ist hier durch, oder?

**Comment by Lednerb** [comment]
@SniperSister nein, das ist noch nicht angepasst. Es wird noch der Single-URL Scan abgerufen.

**Comment by SniperSister** [comment]
In der Staging?

**Comment by SniperSister** [comment]
Ah, du meinst den PDF Report, right? Ok, @sven-ahrens baust du das noch ein?

**Comment by sven-ahrens** [comment]
Jup!

**Comment by sven-ahrens** [comment]
PR dazu ist draußen: https://github.com/SIWECOS/webapp/pull/85

Nun sollten die "neuen" PDFs runtergeladen werden!

**Comment by SniperSister** [comment]
Merged, danke!
