### ISSUE TITLE
Die gewünschte E-Mail-Adresse wird bereits verwendet <- zu unauffällig

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/webapp#6]
Wenn man "Registrieren§ klickt, und die Adresse ist bereits vergeben (vielleicht auch bei anderen Fehlermeldungen?) erscheint der Fehlertext oben, der Button ist unten. Die Fehlermeldung ist höchstwahrescheinlich ausserhalb des Sichtbereichs. Da sich auch nichts am Button tut, ist man versucht, ihn mehrfach zu klicken bevor man merkt, daß irgendwas nicht stimmt.

Hier sollte nachgebessert werden.

Zudem ist der Text wenig auffällig. Eventuell fehlt hier etwas CSS um den Text auffälliger zu gestalten?

**Comment by SniperSister** [comment]
CSS ist angepasst, position auch, bitte nahc dem deploy prüfen

**Comment by Skeeve** [comment]
Super. Gefällt. Eventuell würde ich nur einen bold font für die Schrift wählen. Hier erscheint es etwas dünn. Bitte selbst entscheiden und gegebenenfalls schließen.

**Comment by SniperSister** [comment]
Done!
