### ISSUE TITLE
Anzeige der Scanner-Ergebnisse verbessern

### ISSUE THREAD

**Issue by Lednerb** [SIWECOS/webapp#64]
Die Darstellung der Scanner-Ergebnisse ist suboptimal, wenn der Score bspw. bei 0 und niedrigen Werten ist:

![Bildschirmfoto von 2019-10-25 14-25-36](https://user-images.githubusercontent.com/2056876/67571469-4f29a480-f734-11e9-9884-4e59fcc61f21.png)

Es wäre daher vielleicht besser, wenn der Score-Rand bspw. grau hinterlegt wird, sodass die "Kreise" stets sichtbar sind.

**Comment by Lednerb** [comment]
Auch in der `webapp-freescan` relevant.

**Comment by svom** [comment]
Hierfür war in etwas sowas vorgesehen:
https://codepen.io/ljardin/pen/ZNGKBP

Die Kreise sollen durch einen grauen bzw. nach Möglichkeit einem weniger gesättigten zweiten Kreis hinterlegt werden.

**Comment by sven-ahrens** [comment]
Ich weiß, leider nicht, ob das mit dem kommenden PR von mir gefixt wurde, oder ob das vom Browser abhängig ist, aber bei mir wird sowohl im Chrome, als auch im Firefox dieser "Graue" Kringel angezeigt. Der sollte eigentlich schon lange drin sein.

<img width="728" alt="Bildschirmfoto 2019-10-31 um 11 57 04" src="https://user-images.githubusercontent.com/18313443/67941415-d9ab5180-fbd5-11e9-99e0-c73265c34adf.png">
<img width="789" alt="Bildschirmfoto 2019-10-31 um 11 57 16" src="https://user-images.githubusercontent.com/18313443/67941416-d9ab5180-fbd5-11e9-87bd-69d18fbdb3ac.png">

**Comment by SniperSister** [comment]
@sven-ahrens ich vermute du hast lokal getestet und nicht in der Staging? Dann weiß ich nämlich woran es liegt: die Staging benutzt eine CSP und die verhindert die Nutzung von inline Styles - hab das daher auf SVG attribute umgebaut, siehe #66

**Comment by SniperSister** [comment]
Fixed
