### ISSUE TITLE
Verlinkung zum Wiki einbauen ("Hintergrundinformationen")

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/webapp#71]
Wenn "Hintergrundinformationen" jetzt mit angezeigt werden, sollten wir die Texte der Tests anpassen, damit das hier nicht verwirrt:

<img width="641" alt="image" src="https://user-images.githubusercontent.com/725404/68027559-fbc6d180-fcb2-11e9-9aaa-fa07184c849a.png">

**Comment by sven-ahrens** [comment]
Auf die Texte, auf die Du hier referenzierst, habe ich keinerlei Möglichkeit, die zu bearbeiten, da die aus dem Backend stammen.

**Comment by sven-ahrens** [comment]
Die Frage sollte dann vielleich zu @Lednerb

**Comment by Lednerb** [comment]
@Skeeve die angezeigten Informationen sind nicht die "Hintergrundinformationen" von denen in dem Text die Rede ist. "Hintergrundinformationen" bezieht sich auf den "Hintergrundinformationen"-Link zum Wiki in der aktuellen `production` Version.

@sven-ahrens es wäre praktisch, wenn wir daher noch den Link zum Wiki einbinden könnten und diesen dann einfach "Hintergrundinformationen" nennen.

Andernfalls gehört das Issue ins Translations-Repo und wird dort von Stephan und Petra bearbeitet.

**Comment by Skeeve** [comment]
@Lednerb hat Recht…

![image](https://user-images.githubusercontent.com/725404/68212721-6ab96880-ffda-11e9-8f95-8c2d5dce1cc7.png)

Wir benötigen also nur den Link mit Namen "Hintergrundinformationen"

**Comment by sven-ahrens** [comment]
Ist mit dem nächsten PR drin

**Comment by SniperSister** [comment]
Drin!

**Comment by Skeeve** [comment]
Passt. Danke.
