### ISSUE TITLE
Weniger / Mehr Informationen gerät aus dem Tritt

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/webapp#72]
Repruduzierbar so:
1. "Mehr Informationen" anklicken - Es wird zu "Weniger Informationen"
2. Neuen Scan starten und warten
3. Wenn der Scan zuende ist, werden die Informationen ausgeblendet, der Schriftzug "Weniger Informationen" bleibt.
4. "Weniger Informationen" anklicken und der Schriftzug wird zu "Mehr Informationen". Ausserdem werden die Informationen eingeblendet.

<img width="718" alt="image" src="https://user-images.githubusercontent.com/725404/68081626-7279e100-fe11-11e9-8542-0f2cd5329803.png">

**Comment by sven-ahrens** [comment]
Kann ich reproduzieren. Schau ich mir mal an.

**Comment by Skeeve** [comment]
Gelöst
