### ISSUE TITLE
Interne Scannernamen in der Übersicht?

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/webapp#75]
In der Übersicht werden die internen Scannernamen (INI_S) angezeigt, statt "Initiative-S Scanner" Ist das gewollt?

![image](https://user-images.githubusercontent.com/725404/68214031-f3390880-ffdc-11e9-8dae-68735f17311f.png)

**Comment by Lednerb** [comment]
Für die aktuelle Darstellung wären die Übersetzungen wahrscheinlich zu lang, um dies vernünftig darzustellen?

Wir könnten bei den Scanner-Namen das jeweilige Kürzel mit Angeben, bspw. weiter unten dann "Initiative-S Scanner [INI_S]" bzw. das `[INI_S]` als Tag darstellen etc.?

**Comment by sven-ahrens** [comment]
Könnte ich machen!

**Comment by sven-ahrens** [comment]
<img width="802" alt="Bildschirmfoto 2019-11-05 um 16 19 25" src="https://user-images.githubusercontent.com/18313443/68220436-0dc4af00-ffe8-11e9-90d9-96d18124e764.png">

**Comment by SniperSister** [comment]
Ist drin!

**Comment by Skeeve** [comment]
Passt. Danke.
