### ISSUE TITLE
Jumps funktionieren nicht

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/webapp#76]
Die Links von der Übersicht zum Scanner funktionieren nicht.

`<a href="#327_POP3_TLS">`

Die id lautet aber

`<section id="327_POP3(STARTTLS) Scanner" class="detail__contentsection">`

Hängt vermutlich mit #75 zusammen.

Die Zurück-Links sind nicht sichtbar:

```
<a href="#327" class="jumplink">
      Zurück zur Übersicht
    </a>
```

**Comment by sven-ahrens** [comment]
Also die jumplinks werden im nächsten PR wieder funktionieren, der "Zurück zur Übersicht" Button, muss im CSS verändert werden. Spreche da nochmal mit David.

Der hat nen ``position: absolute; left: 999999px``, da kann der natürlich nicht gesehen werden.

**Comment by Skeeve** [comment]
Passt. Danke.
