### ISSUE TITLE
Anzeige der URLs anpassen

### ISSUE THREAD

**Issue by Lednerb** [SIWECOS/webapp#77]
Momentan werden in `staging` jeweils nur weitere URLs, abgesehen von der Haupt-URL [http(s)://domain.tld] angezeigt.

Es wäre dabei auch wichtig, die entsprechende Haupt-URL mit auszugeben, die die gleichen Ergebnisse aufweisen.

Momentan lässt sich hier bspw. nicht feststellen, wieso der DOMXSS-Scanner lediglich 50 Punkte erreichte:

![Bildschirmfoto von 2019-11-05 15-27-46](https://user-images.githubusercontent.com/2056876/68216895-f5ea2c80-ffe1-11e9-92c3-543f9f5aaf70.png)

-------------------

Weiterhin sollte die Überschrift dann in "Domains / URLs" umbenannt werden, da bspw. bei den *_TLS -Scannern sowie dem INI_S-Scanner keine URLs gescannt werden.

**Comment by SniperSister** [comment]
wohl mit #79 mit gefixt, prüfst du das kurz?

**Comment by Lednerb** [comment]
Leider noch nicht behoben, bzw. nicht ganz wie erwartet:

A: Bei meinem aktuellen Scan, wurden mind. 4 Domains mit dem INI-S-Scanner geprüft (Haupt-Domain und 3 MailDomains). Zwar gab es keinen Fehler, ich kann aber als Nutzer auch nicht feststellen, welche Domains tatsächlich geprüft wurden:

![Bildschirmfoto von 2019-11-12 17-39-27](https://user-images.githubusercontent.com/2056876/68691232-b4262c80-0573-11ea-8a42-baa20307a97e.png)


Vielleicht sollte daher generell die Ausgabe mit den Domains / URLs angezeigt werden, also auch bei erfolgreichen Tests? (CC @Skeeve)

-----------------------------------

B: Wurde auf der Hauptseite nichts problematisches von den Scannern erkannt, auf einer Unterseite jedoch ein Fehler gemeldet, scheint die Ausgabe das positive Ergebnis zu unterschlagen:

![Bildschirmfoto von 2019-11-12 17-47-46](https://user-images.githubusercontent.com/2056876/68691834-b2a93400-0574-11ea-8c67-8b0f2cb2f006.png)

Als Ergebnis müsste daher meiner Meinung nach angezeigt werden:

1. Es wurden keine DOMXSS-Sources gefunden
- `https://lednerb.eu`

2. Der Scanner hat keine Skript-Inhalte zum Bewerten gefunden
- `https://lednerb.eu/site.webmanifest`

Gleiches mit den Sinks.


Interessant wird dies vor allem, wenn bspw. der HEADER-Scanner sehr viele verschiedene Kombinationen von Headern findet. Da sollten dann auch die erfolgreichen URIs aufgelistet sein und je nach Ergebnis gruppiert sämtliche passende URIs.

**Comment by SniperSister** [comment]
Bei  B) bin ich bei dir, bei A) aber anderer Meinung: wenn alles in Ordnung ist, sehe ich keinen Mehrwert in der URL-Liste

**Comment by Skeeve** [comment]
Frage 3 Leute und Du bekommst 4 Meinungen… ;) Naja… Hier die dritte Meinung…

Bei B) Stimme ich erstmal Euch beiden zu.

Für A stime ich Sascha zu, dass es schön wäre zu wissen, welche Domains gescannt wurden, stimme aber auch David zu, dass es für gute Ergebnisse, und wir wollen ja nur gute, eine nutzlose Redundanz ist.

Warum also nicht ein zusätzliches "Testergebnis" in der Übersicht ausklapbar machen "Getestete Domains und URLs" und dort alle aufzulisten? Entweder auf Ebene der Eingetragenen Domains oder, wenn das nicht sinnvoll ist, auf Ebene der Scanner.

**Comment by SniperSister** [comment]
Das wäre dann die 4te ? Ausklappebene in der Ansicht, das ist in meinen Augen einfach zu viel des Guten, insbesondere da sie sich ja an vielen Stellen dann endlos wiederholen wird.

**Comment by Skeeve** [comment]
Nein, @SniperSister … Ich dachte an genau ein Ausklappfenster pro registrierter Domain.

<img width="762" alt="image" src="https://user-images.githubusercontent.com/725404/68742621-e629a400-05f0-11ea-8984-5d8eb3ed2671.png">

**Comment by SniperSister** [comment]
Bauchgefühl: wenn ich hier die Vorteile (Informationen mit Relevanz für einen kleinen Teil der Nutzer) mit den Nachteilen abwägen (Yet another Ausklappbereich, Yet another Button, Programmieraufwand) dann lohnt sich das nicht

**Comment by Skeeve** [comment]
Ohne Ausklappen und am Ende - Zuviel Aufwand? Dann halt meinetwegen nicht ;)

Bleibt B…

**Comment by SniperSister** [comment]
> Als Ergebnis müsste daher meiner Meinung nach angezeigt werden:

Haben uns B) gerade nochmal genauer angeschaut: sobald bei 50 URLs eine mit fehler dabei ist, willst du das das UI die 49 anderen ohne Fehler ebenfalls auflistet, korrekt @Lednerb ? Das klingt nach extrem viel "Noise" bei sehr wenig "Signal". 

Daher ist mein Proposal nach wie vor: erfolgreiche URLs nicht anzeigen, fehlerhafte URLs nach Fehler gruppiert anzeigen.

**Comment by Skeeve** [comment]
> Daher ist mein Proposal nach wie vor: erfolgreiche URLs nicht anzeigen, fehlerhafte URLs nach Fehler gruppiert anzeigen.

Genau so. Wobei ich immer noch gerne alle URLs an einer Stelle würde lesen kennen.

**Comment by SniperSister** [comment]
Ok, dann kompromiss:

* Erfolgreiche URLs bei den Tests NICHT anzeigen
* Dafür eine Liste von *allen* URLs wie in https://github.com/SIWECOS/webapp/issues/77#issuecomment-553278193

**Comment by sven-ahrens** [comment]
Finde ich gut so

**Comment by sven-ahrens** [comment]
Ansonsten ist das ja auch redundant, wenn man gefühlt bei 80% der Tests immer und immer wieder die "erfolgreichen" URLs / Domains anzeigen lässt

**Comment by SniperSister** [comment]
Ok, dann machen wir das so!

**Comment by SniperSister** [comment]
@Skeeve @Lednerb deploy läuft, danach in der staging verfügbar. Brauch noch Styling, aber Logik sollte passen. Bitte dann prüfen

**Comment by Skeeve** [comment]
Schön ist, dass wir oben eine Liste der Domains/URLs haben.

Unschön ist, dass wir für Meldungen wie 

```
Automatisiert wurden keine unsicheren Codebestandteile für DOMXSS-Sinks erkannt.

Der Scanner hat keine Skript-Inhalte zum Bewerten gefunden.
```

Auch die betreffenden Adressen sehen. Aber das liegt eher am Scanner, nehme ich an. Würde er die nicht mitliefern, sähen wir sie auch nicht.


Der Port Scanner gibt noch eine merkwürdige Meldung aus:
<img width="677" alt="image" src="https://user-images.githubusercontent.com/725404/69231041-b0546480-0b88-11ea-9d4b-43a43d58e504.png">

Ich nehme an, das sollte ein Ticket für den ergeben, oder?

**Comment by SniperSister** [comment]
> Ich nehme an, das sollte ein Ticket für den ergeben, oder?

Yes

**Comment by Lednerb** [comment]
@Skeeve 

> Auch die betreffenden Adressen sehen. Aber das liegt eher am Scanner, nehme ich an. Würde er die nicht mitliefern, sähen wir sie auch nicht.

Nein, das wäre nicht Aufgabe des Scanners, da die Ausgabe trivial ist:
Der Scanner scannt die URL XYZ, dann ist das Ergebnis logischerweise auch für XYZ gemeint.

Die Ausgabe müsste das Frontend abbilden, welches die benötigten Informationen bereits erhält.

Diese Problembeschreibung meinte ich mit *B:* hier https://github.com/SIWECOS/webapp/issues/77#issuecomment-552982730

Vorschlag B wurde dann mit deiner Zustimmung verworfen https://github.com/SIWECOS/webapp/issues/77#issuecomment-553892445 ;-)

**Comment by SniperSister** [comment]
@sven-ahrens bei erfolgreichen Tests (score 100, has_error false) müssen keine URLs ausgegeben werden - da kann die Gruppierung geskippt werden

**Comment by SniperSister** [comment]
@Lednerb @Skeeve wir haben das beim DOMXSS nochmal angeschaut:
aktuell bleben wir die URLs aus, wenn score 100, has_error false und score_type = success ist - der domxss gibt aber score_type = info und wird daher angezeigt. Soll dann die prüfung auf Score-Type raus?

**Comment by Lednerb** [comment]
Beim DOMXSS hatten wir den `score_type: info` eingeführt, da in der ersten Version dann danach gefiltert werden sollte, ob der Score mit in die Berechnung einfließt bzw. um den DOMXSS-Scanner als reinen `info`-Scanner zu markieren.

Es macht aber mehr Sinn, den DOMXSS-Scanner auf `success` anzupassen, da der Scanner nichts mit unserer Bewertung im Nachhinein zu tun hat.

Dann kann das so bleiben. Ich öffne entsprechende Issues für den DOMXSS und HEADER Scanner.

**Comment by SniperSister** [comment]
Perfekt, dann ist ds durch, danke!
