### ISSUE TITLE
Webapp (vermutlich auch freeapp) kommt nicht mit Zeitzone zurecht

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/webapp#8]
webapp zeigt UTC+2 (Sommerzeit)

![webapp](https://user-images.githubusercontent.com/725404/48259236-aba68d80-e417-11e8-8fa2-f510e14521ad.png)

während freeapp UTC+1 (Normalzeit) zeigt.

![freeapp](https://user-images.githubusercontent.com/725404/48259268-beb95d80-e417-11e8-8152-7af2150baa8c.png)

**Comment by Skeeve** [comment]
Vielleicht hilft http://www.onlineaspect.com/2007/06/08/auto-detect-a-time-zone-with-javascript/

**Comment by SniperSister** [comment]
In der Staging gefixt, bitte testen

**Comment by SniperSister** [comment]
@Skeeve

**Comment by Skeeve** [comment]
Sieht gut aus!

Gerade auf die Zeitzone von Peru umgestellt und sie wird in der webapp angepaßt.

TOP!

**Comment by SniperSister** [comment]
Jut, cherry picked to master und gepushed, deploy läuft.
