### ISSUE TITLE
Anpassung Kontraste / Schriftgröße

### ISSUE THREAD

**Issue by Lednerb** [SIWECOS/webapp#81]
Die Links "Mehr Informationen" / "Weniger Informationen" sind sehr schlecht lesbar, da zu wenig Kontrast (je nach Bildschirm Auflösung und Helligkeit).
Gerade auch für Menschen mit eingeschränkter Sehfähigkeit sollte dieser Kontrast stärker ausfallen.

Außerdem wird in der Auflistung der Domains / URLs mit Hintergrund-Streifen gearbeitet.

Im angehängten Screenshot scheint die letzte URL jedoch "einfach da zu hängen".

Entweder auf die Streifen verzichten, oder anstatt weiß einen etwas helleren Hintergrund als für die ungeraden Zeilen verwenden.

![Bildschirmfoto von 2019-11-12 17-53-12](https://user-images.githubusercontent.com/2056876/68692420-c012ee00-0575-11ea-98d9-27b3a9c6566a.png)

------------------------

Der "Zurück zur Übersicht" Link erscheint mir hingegen als etwas zu groß.

**Comment by SniperSister** [comment]
> Die Links "Mehr Informationen" / "Weniger Informationen" sind sehr schlecht lesbar,

Deploy dafür läuft

> Im angehängten Screenshot scheint die letzte URL jedoch "einfach da zu hängen".

Das finde ich ehrlich gesagt unproblematisch. Das Pattern ist gängig, dafür würde ich kein Fass auf machen.

> Der "Zurück zur Übersicht" Link erscheint mir hingegen als etwas zu groß.

Die finde ich ehrlich gesagt grundsätzlich recht sinnfrei. Hab sie aber in der Größe angepasst.

**Comment by Lednerb** [comment]
Deploy war offenbar nicht erfolgreich:
https://travis-ci.org/SIWECOS/siwecos-website/builds/610966343

**Comment by SniperSister** [comment]
fixed
