### ISSUE TITLE
Passwort zurücksetzen funktioniert nicht

### ISSUE THREAD

**Issue by PetraStruck** [SIWECOS/webapp#86]
Wenn ein Kunde "Passwort vergessen" anklickt, erhält er eine Mail mit einem Link zum Zurücksetzen des Passwortes. Beim Klick auf den Link  in der Mail erscheint die normale Login-Maske ohne eine Möglichkeit, ein neues Passwort einzugeben.

**Comment by SniperSister** [comment]
@PetraStruck Fix dafür ist fertig, warte auf Core-Review, siehe #87

**Comment by SniperSister** [comment]
@PetraStruck Fix ist im Deployment, sollte in ca. 15min online sein
