### ISSUE TITLE
Keine Fehlermeldung beim Eintragen einer Domain die nicht antwortet.

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/webapp#9]
Der Versuch https://gibt.es einzutragen wird ohne Fehlermeldung nicht durchgeführt. Test mit curl zeigt, daß die Domain nicht antowrtet (Connect timeout). Webkonsole zeigt einen "502".

Dem Nutzer wird aber keine Fehlermeldung angezeigt.

**Comment by SniperSister** [comment]
@Skeeve im Freescan gefixt
